# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'scanner_window.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Scanner_Window(object):
    def setupUi(self, Scanner_Window):
        Scanner_Window.setObjectName("Scanner_Window")
        Scanner_Window.resize(730, 659)
        self.gridLayoutWidget = QtWidgets.QWidget(Scanner_Window)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 10, 701, 160))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.labelStatus = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.labelStatus.setFont(font)
        self.labelStatus.setObjectName("labelStatus")
        self.gridLayout.addWidget(self.labelStatus, 3, 0, 1, 3)
        self.pushConnect = QtWidgets.QPushButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushConnect.setFont(font)
        self.pushConnect.setObjectName("pushConnect")
        self.gridLayout.addWidget(self.pushConnect, 4, 0, 1, 1)
        self.pushDisconnect = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushDisconnect.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushDisconnect.setFont(font)
        self.pushDisconnect.setObjectName("pushDisconnect")
        self.gridLayout.addWidget(self.pushDisconnect, 4, 2, 1, 1)
        self.linePassword = QtWidgets.QLineEdit(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.linePassword.setFont(font)
        self.linePassword.setObjectName("linePassword")
        self.gridLayout.addWidget(self.linePassword, 2, 2, 1, 1)
        self.lineAddress = QtWidgets.QLineEdit(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineAddress.setFont(font)
        self.lineAddress.setObjectName("lineAddress")
        self.gridLayout.addWidget(self.lineAddress, 2, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 1, 2, 1, 1)
        self.linePort = QtWidgets.QLineEdit(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.linePort.setFont(font)
        self.linePort.setObjectName("linePort")
        self.gridLayout.addWidget(self.linePort, 2, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 1, 1, 1, 1)
        self.labelOn = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.labelOn.setFont(font)
        self.labelOn.setObjectName("labelOn")
        self.gridLayout.addWidget(self.labelOn, 5, 0, 1, 1)
        self.gridLayoutWidget_2 = QtWidgets.QWidget(Scanner_Window)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(10, 150, 701, 261))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.pushOff = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.pushOff.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushOff.setFont(font)
        self.pushOff.setObjectName("pushOff")
        self.gridLayout_2.addWidget(self.pushOff, 4, 1, 1, 1)
        self.pushClear = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.pushClear.setEnabled(True)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushClear.setFont(font)
        self.pushClear.setObjectName("pushClear")
        self.gridLayout_2.addWidget(self.pushClear, 4, 2, 1, 1)
        self.spinTime = QtWidgets.QSpinBox(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.spinTime.setFont(font)
        self.spinTime.setMinimum(1)
        self.spinTime.setMaximum(100)
        self.spinTime.setObjectName("spinTime")
        self.gridLayout_2.addWidget(self.spinTime, 3, 0, 1, 1)
        self.pushOn = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.pushOn.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushOn.setFont(font)
        self.pushOn.setObjectName("pushOn")
        self.gridLayout_2.addWidget(self.pushOn, 4, 0, 1, 1)
        self.pushSave = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.pushSave.setEnabled(True)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushSave.setFont(font)
        self.pushSave.setObjectName("pushSave")
        self.gridLayout_2.addWidget(self.pushSave, 4, 3, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.gridLayout_2.addWidget(self.label_5, 2, 0, 1, 1)
        self.labelNum = QtWidgets.QLabel(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.labelNum.setFont(font)
        self.labelNum.setObjectName("labelNum")
        self.gridLayout_2.addWidget(self.labelNum, 1, 0, 1, 1)
        self.listCodes = QtWidgets.QListWidget(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(12)
        self.listCodes.setFont(font)
        self.listCodes.setObjectName("listCodes")
        self.gridLayout_2.addWidget(self.listCodes, 0, 1, 4, 3)
        self.gridLayoutWidget_3 = QtWidgets.QWidget(Scanner_Window)
        self.gridLayoutWidget_3.setGeometry(QtCore.QRect(10, 420, 701, 237))
        self.gridLayoutWidget_3.setObjectName("gridLayoutWidget_3")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.gridLayoutWidget_3)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.pushDownload = QtWidgets.QPushButton(self.gridLayoutWidget_3)
        self.pushDownload.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushDownload.setFont(font)
        self.pushDownload.setObjectName("pushDownload")
        self.gridLayout_3.addWidget(self.pushDownload, 4, 0, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.gridLayout_3.addWidget(self.label_6, 1, 0, 1, 1)
        self.labelCurrent = QtWidgets.QLabel(self.gridLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.labelCurrent.setFont(font)
        self.labelCurrent.setObjectName("labelCurrent")
        self.gridLayout_3.addWidget(self.labelCurrent, 0, 0, 1, 1)
        self.listSessions = QtWidgets.QListWidget(self.gridLayoutWidget_3)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(12)
        self.listSessions.setFont(font)
        self.listSessions.setObjectName("listSessions")
        self.gridLayout_3.addWidget(self.listSessions, 2, 0, 1, 3)
        self.listCurrent = QtWidgets.QListWidget(self.gridLayoutWidget_3)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(12)
        self.listCurrent.setFont(font)
        self.listCurrent.setObjectName("listCurrent")
        self.gridLayout_3.addWidget(self.listCurrent, 2, 3, 1, 2)
        self.pushRemove = QtWidgets.QPushButton(self.gridLayoutWidget_3)
        self.pushRemove.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushRemove.setFont(font)
        self.pushRemove.setObjectName("pushRemove")
        self.gridLayout_3.addWidget(self.pushRemove, 4, 1, 1, 1)
        self.pushCreate = QtWidgets.QPushButton(self.gridLayoutWidget_3)
        self.pushCreate.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushCreate.setFont(font)
        self.pushCreate.setObjectName("pushCreate")
        self.gridLayout_3.addWidget(self.pushCreate, 4, 2, 1, 1)
        self.pushMakeCurrent = QtWidgets.QPushButton(self.gridLayoutWidget_3)
        self.pushMakeCurrent.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushMakeCurrent.setFont(font)
        self.pushMakeCurrent.setObjectName("pushMakeCurrent")
        self.gridLayout_3.addWidget(self.pushMakeCurrent, 4, 3, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.gridLayout_3.addWidget(self.label_7, 1, 3, 1, 1)

        self.retranslateUi(Scanner_Window)
        QtCore.QMetaObject.connectSlotsByName(Scanner_Window)

    def retranslateUi(self, Scanner_Window):
        _translate = QtCore.QCoreApplication.translate
        Scanner_Window.setWindowTitle(_translate("Scanner_Window", "Работа со сканером штрихкодов"))
        self.labelStatus.setText(_translate("Scanner_Window", "Статус: отключен"))
        self.pushConnect.setText(_translate("Scanner_Window", "Подключить"))
        self.pushDisconnect.setText(_translate("Scanner_Window", "Отключить"))
        self.linePassword.setText(_translate("Scanner_Window", "1234"))
        self.lineAddress.setText(_translate("Scanner_Window", "192.168.43.87"))
        self.label_2.setText(_translate("Scanner_Window", "Сетевой адрес:"))
        self.label_3.setText(_translate("Scanner_Window", "Пароль"))
        self.linePort.setText(_translate("Scanner_Window", "9090"))
        self.label.setText(_translate("Scanner_Window", "Параметры соединения:"))
        self.label_4.setText(_translate("Scanner_Window", "Порт"))
        self.labelOn.setText(_translate("Scanner_Window", "Онлайн режим:OFF"))
        self.pushOff.setText(_translate("Scanner_Window", "Выключить"))
        self.pushClear.setText(_translate("Scanner_Window", "Очистить"))
        self.pushOn.setText(_translate("Scanner_Window", "Включить"))
        self.pushSave.setText(_translate("Scanner_Window", "Сохранить"))
        self.label_5.setText(_translate("Scanner_Window", "Время обновления , с"))
        self.labelNum.setText(_translate("Scanner_Window", "Всего:0"))
        self.pushDownload.setText(_translate("Scanner_Window", "Скачать"))
        self.label_6.setText(_translate("Scanner_Window", "Список сессий:"))
        self.labelCurrent.setText(_translate("Scanner_Window", "Текущая сессия:"))
        self.pushRemove.setText(_translate("Scanner_Window", "Удалить"))
        self.pushCreate.setText(_translate("Scanner_Window", "Создать"))
        self.pushMakeCurrent.setText(_translate("Scanner_Window", "Сделать текущей"))
        self.label_7.setText(_translate("Scanner_Window", "Содержание выбранной сессии:"))
